### ISSUE TITLE
Application hangs after clicking on checkout button

### ISSUE THREAD

**Issue by Vityn** [paypal/paypalcheckout-samples-ios#11]
I followed all the instruction provided in the readme and launched the application in both real and simulator devices.
Clicking on "checkout with order" button, and inserting my personal sandbox paypal account, the application hangs and does not complete the operation.
Attached a screenshot picked from the device:

<img width="150" alt="Schermata 2021-05-11 alle 22 27 18" src="https://user-images.githubusercontent.com/48033451/117882980-297ad680-b2ab-11eb-8c60-6642c632e828.png">

**Comment by Pelican43** [comment]
Hi,

Same here.Have you found a solution ?

Best regards.

**Comment by jaxdesmarais** [comment]
Hello @Vityn and @Pelican43 -

Thanks for reporting this issue. Typically the resolution in this case is an issue with the `returnUrl`. Two suggestions:

1. Check that the `returnUrl` being provided in the developer dashboard exactly matches what you are supplying in your config
2. We've seen some issues with capital letters in the `returnUrl` causing hangups in our auth SDK. Make sure your `returnUrl` in both the developer dashboard and the config are lowercased.

If either of you are still running into issues after trying the above, please [report the issue on our SDK repo](https://github.com/paypal/paypalcheckout-ios/issues) along with steps for us to reproduce.
